// Language list with ISO 639-2 codes and full names
export const languages = [
  { code: "eng", name: "English" },
  { code: "hin", name: "Hindi" },
  { code: "ben", name: "Bengali" },
  { code: "tam", name: "Tamil" },
  { code: "tel", name: "Telugu" },
  { code: "kan", name: "Kannada" },
  // { code: "asm", name: "Assamese" },
  // { code: "bho", name: "Bhojpuri" },
  // { code: "doi", name: "Dogri" },
  // { code: "guj", name: "Gujarati" },
  // { code: "kas", name: "Kashmiri" },
  // { code: "kok", name: "Konkani" },
  // { code: "mai", name: "Maithili" },
  // { code: "mal", name: "Malayalam" },
  // { code: "mar", name: "Marathi" },
  // { code: "mni", name: "Manipuri (Meitei)" },
  // { code: "ori", name: "Odia" },
  // { code: "pan", name: "Punjabi" },
  // { code: "san", name: "Sanskrit" },
  // { code: "sind", name: "Sindhi" },
  // { code: "urd", name: "Urdu" },
  // { code: "anp", name: "Angika" },
  // { code: "awa", name: "Awadhi" },
  // { code: "bra", name: "Braj" },
  // { code: "gon", name: "Gondi" },
  // { code: "kha", name: "Khasi" },
  // { code: "sat", name: "Santali" },
  // { code: "sck", name: "Sadri" },
  // { code: "lep", name: "Lepcha" },
  // { code: "nep", name: "Nepali" },
];